accounts:
  - uid: 100000
    # 小米账户ID 非小米账户用户名
    password: Abcd.1234
    # 小米账户密码或其MD5哈希
    user-agent: 'Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0'
    # 登录小米社区时所用浏览器的 User-Agent
    # 可在此工具查看：https://tool.chinaz.com/useragent
    carrot-pull: false
    # 小米社区拔萝卜，可能存在封号风险
    check-in: false
    # 小米社区成长值签到，可能存在封号风险
    # 本脚本默认完成登录社区和三次点赞及三次浏览十秒帖子的成长值任务
# 若有多个小米账户，按照以下模板进行修改，使用时删除前端 #注释
#  - uid: 100001
#    password: abc123
#    user-agent: 'Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0'
#    carrot-pull: false
#    check-in: false
logging: false
# 归档日志到本地文件
version: v1.5.1
# config 文件版本号，debug用
