accounts:
  - uid: 100000
    # 账户ID 非账户用户名或手机号
    password: Abcd.1234
    # 账户密码或其MD5哈希
    user-agent: 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Safari/537.36'
    # 登录社区时所用浏览器的 User-Agent
    # 可在此工具查看：https://tool.chinaz.com/useragent
    
    # 功能开关
    check-in: false
    # 社区成长值签到，可能存在封号风险
    browse-user-page: false
    # 社区浏览个人主页10秒，可能存在封号风险
    browse-post: false
    # 社区浏览帖子10秒，可能存在封号风险
    thumb-up: false
    # 点赞帖子，可能存在封号风险
    browse-specialpage: false
    # 社区在活动期间可能会出现限时的“浏览指定专题页”任务，可能存在封号风险
    board-follow: false
    # 社区可能会出现限时的“加入圈子”任务，可能存在封号风险
    carrot-pull: false
    # 社区拔萝卜，可能存在封号风险

# 若有多个账户，按照以下模板进行修改，使用时删除前端 #注释
#  - uid: 100001
#    password: abc123
#    user-agent: 'Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0'
#    check-in: false
#    browse-user-page: false
#    browse-post: false
#    thumb-up: false
#    browse-specialpage: false
#    board-follow: false
#    carrot-pull: false
ONEPUSH:
  notifier: telegram
  params:
    title:
    markdown: false
    token:
    userid:

logging: false
# 归档日志到本地文件
version: v1.6.0
# config 文件版本号，debug用
