name: 功能请求
description: Suggest an idea for this project
title: "[Feature] 请在这块简要说明需求，否则该issue将会被关闭"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        如果你可以自己 编程实现 的话, 建议您直接提交 PR 或 描述解决方法, 非常感谢!
  - type: checkboxes
    id: verify_step
    attributes:
      label: Verify Steps
      description: "在提交之前，请确认 / Please verify that you've followed these steps"
      options:
        - label: Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
          required: true
        - label: Need 当前 MIUITask 并不包含该功能特性或者还不完善
          required: true
        - label: Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
          required: true
        - label: Meaningful 我提交的不是无意义的 催促更新或修复 请求
          required: true
  - type: textarea
    attributes:
      label: Describe the Feature
      description: |
        对问题本身清晰而简洁的描述. 例如这个问题如何影响到你? 目前 MIUITask 的行为是什么?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Solution
      description: |
        清晰明了地描述您的解决方案. 例如你想实现什么 Feature 特性或功能? 如何实现该功能? 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe Alternatives
      description: |
        对您考虑过的任何替代解决方案或备选功能进行清晰、简洁的描述.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        在此处添加关于功能请求的任何其他描述或屏幕截图.
    validations:
      required: false
