name: test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
         fetch-depth: 0
         fetch-tags: true

      - name: Use the output
        run: |
          git describe --tags --abbrev=0
          
      - name: test
        id: generate_changelog
        uses: Night-stars-1/changelog-generator-action@main

      - name: Use the output
        run: |
          echo "Generated changelog:"
          echo "${{ steps.generate_changelog.outputs.changelog }}"
